<?php
/** @var mxreCaptcha\Form\Element\ReCaptcha $element */
$element = $this->element;
$id      = 'mxreCaptcha_element_' . substr(md5(uniqid(mt_rand(0,1000000), true)), 0, 5);
?>

<div class="mxreCaptcha" id="<?= $id ?>"></div>
<input type="hidden" name="<?= $element->getName() ?>" value="1">
<script type="text/javascript">
    var mxreCaptchaOnLoadCallback = function() {
        grecaptcha.render('<?= $id ?>', <?= $this->options ?>);
    };
</script>
<script src="https://www.google.com/recaptcha/api.js?onload=mxreCaptchaOnLoadCallback&amp;render=explicit" async defer></script>
